# Generated by Django 2.2.5 on 2019-10-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('prod_desc', models.TextField()),
                ('order_crtdate', models.DateTimeField()),
                ('price_total', models.FloatField()),
                ('rs', models.IntegerField()),
            ],
        ),
    ]
